config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"

  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :prefix, presence: true
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :gender, presence: true
  validates :email, presence: true
  validates :medicare, presence: true, length: { is: 10 }
  validates :IRN, presence: true, length: { is: 1 }
  validates :dob, presence: true
  validates :phoneNumber, presence: true, length: { is: 10 }
  validates :address, presence: true
  validates :suburb, presence: true
  validates :state, presence: true
  validates :postcode, presence: true, length: { is: 4 }
  validates :notes, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else
      render :new
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to "/patients"
  end

  private
    def patient_params
      params.require(:patient).permit(:prefix, :firstName, :lastName, :gender, :email, :medicare, :IRN, :dob, :phoneNumber, :address, :suburb, :state, :postcode, :notes, :medications, :medicalHistory)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenHospital</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">OpenHospital</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/patients">Patients</a>
            </li>
        </div>
        <div class="d-flex">
          <a href="<%= new_patient_path %>"><button type="button" class="btn btn-primary">Enroll New Patient</button></a>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <div>
      <hr class='footer' />
      <p class='text-center'>© Jesse Lyon 2021</p>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to OpenHospital!</h1>
  <p class="lead">OpenHospital allows for patients management. <span id='user-warning'>PLEASE NOTE: ONLY AUTHROISED USERS ARE PERMITTED TO ACCESS THIS SOFTWARE.</span></p>
</div>

app/views/patients/_form.html.erb
<%= form_with model: @patient do |form| %>
  <% if @patient.errors.full_messages.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :prefix %><br>
    <%= form.select :prefix, ["Mr.", "Ms.", "Miss.", "Mrs.", "Mst."] %>
  </div>
  
  
  <div>
    <%= form.label :firstName, "First Name" %><br>
    <%= form.text_field :firstName %>
  </div>
  
  <div>
    <%= form.label :lastName, "Last Name" %><br>
    <%= form.text_field :lastName %>
  </div>

  <div>
    <%= form.label :gender %><br>
    <%= form.select :gender, ["Male", "Female", "Other"] %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>
  
  <div>
    <%= form.label :medicare %><br>
    <%= form.text_field :medicare %>
  </div>

  <div>
    <%= form.label :IRN, "Individual Reference Number" %><br>
    <%= form.text_field :IRN %>
  </div>

  <div>
    <%= form.label :dob, "Date of Birth" %><br>
    <%= form.text_field :dob, placeholder: "DD/MM/YYYY" %>
  </div>

  <div>
    <%= form.label :phoneNumber, "Phone Number" %><br>
    <%= form.telephone_field :phoneNumber %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :suburb %><br>
    <%= form.text_field :suburb %>
  </div>

  <div>
    <%= form.label :state %><br>
    <%= form.select :state, ["VIC", "NSW", "QLD", "SA", "NT", "WA", "ACT", "TAS"] %>
  </div>

  <div>
    <%= form.label :postcode %><br>
    <%= form.text_field :postcode %>
  </div>

  <div>
    <%= form.label :notes %><br>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.label :medications %><br>
    <%= form.text_area :medications %>
  </div>

  <div>
    <%= form.label :medicalHistory, "Medical History" %><br>
    <%= form.text_area :medicalHistory %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<div class="row">
  <div class="jumbotron">
    <h1>Edit Patient</h1>

    <%= render "form", patient: @patient %>
  </div>
</div>

app/views/patients/index.html.erb
<div class="row">
  <h1>Patients</h1>
</div>

<div class="row">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Date of Birth</th>
        <th scope="col">Address</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <th scope="row"><a href="<%= patient_path(patient) %>"><%= patient.prefix + " " + patient.lastName + ", " + patient.firstName %></a></th>
          <td><%= patient.dob %></td>
          <td><%= patient.address %></td>
        </tr> 
      <% end %>
    </tbody>
  </table>
</div>

app/views/patients/new.html.erb
<div class="row">
  <div class="jumbotron">
    <h1>New Patient</h1>

    <%= render "form", patient: @patient %>
  </div>
</div>

app/views/patients/show.html.erb
<div class="jumbotron">
  <h1><%= @patient.prefix + " " + @patient.lastName + ", " + @patient.firstName %></h1>
  <h3>Patient ID: <%= @patient.id %></h3>
  <hr />
  <div class="row">
    <div class="col">
      <p><strong>Date of Birth:</strong> <%= @patient.dob %></p>
      <p><strong>Gender:</strong> <%= @patient.gender %></p>
      <p><strong>Email:</strong> <a href="mailto:<%= @patient.email %>"><%= @patient.email %></a></p>
      <p><strong>Mobile:</strong> <a href="tel:<%= @patient.phoneNumber %>"><%= @patient.phoneNumber %></a></p>
      <p><strong>Medicare:</strong> <%= @patient.medicare + " " + @patient.IRN %></p>
      <p><strong>Address:</strong></p>
      <p><%= @patient.address %></p>
      <p><%= @patient.suburb + ", " + @patient.state + " " + @patient.postcode %></p>
    </div>
    <div class="col">
      <strong>Notes:</strong>
      <p><%= @patient.notes %></p>

      <strong>Medications:</strong>
      <p><%= @patient.medications %></p>

      <strong>Medical History:</strong>
      <p><%= @patient.medicalHistory %></p>

      <p><strong>Created At: </strong><%= @patient.created_at %></p>
      <p><strong>Updated At: </strong><%= @patient.updated_at %></p>
    </div>
  </div>
  
  <%= link_to "Edit Patient", edit_patient_path(@patient), :class=>"btn btn-block btn-warning" %>
  <%= link_to "Delete Patient", patient_path(@patient), method: :delete, :class=>"btn btn-block btn-danger" %>
</div>